config/routes.rb
Rails.application.routes.draw do
  resources :phone_numbers
  devise_for :users
  root 'static#home'
  get 'twilio', to: 'webhook#twilio'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/phone_number.rb
class PhoneNumber < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  # https://github.com/heartcombo/devise#strong-parameters
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:twilio_auth_token, :twilio_account_sid])
  end
end

app/controllers/phone_numbers_controller.rb
class PhoneNumbersController < ApplicationController
  before_action :set_phone_number, only: %i[ edit update destroy ]

  # GET /phone_numbers or /phone_numbers.json
  def index
    @phone_numbers = client.incoming_phone_numbers.list
  end

  # GET /phone_numbers/+14044062468
  def show
    @phone_number = client.incoming_phone_numbers.list(phone_number: params[:id]).first
    @messages = Message.where(to: @phone_number.phone_number).first(100)
  end

  # GET /phone_numbers/new
  def new
    @phone_number = PhoneNumber.new
  end

  # GET /phone_numbers/1/edit
  def edit
  end

  # POST /phone_numbers or /phone_numbers.json
  def create
    @phone_number = PhoneNumber.new(phone_number_params)

    respond_to do |format|
      if @phone_number.save
        format.html { redirect_to @phone_number, notice: "Phone number was successfully created." }
        format.json { render :show, status: :created, location: @phone_number }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @phone_number.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /phone_numbers/1 or /phone_numbers/1.json
  def update
    respond_to do |format|
      if @phone_number.update(phone_number_params)
        format.html { redirect_to @phone_number, notice: "Phone number was successfully updated." }
        format.json { render :show, status: :ok, location: @phone_number }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @phone_number.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phone_numbers/1 or /phone_numbers/1.json
  def destroy
    @phone_number.destroy
    respond_to do |format|
      format.html { redirect_to phone_numbers_url, notice: "Phone number was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def client
      Twilio::REST::Client.new current_user.twilio_account_sid, current_user.twilio_auth_token
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_phone_number
      @phone_number = PhoneNumber.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def phone_number_params
      params.require(:phone_number).permit(:e164_number, :twilio_sid)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home; end
end

app/controllers/webhook_controller.rb
class WebhookController < ApplicationController
  before_action :authorize_twilio, only: :twilio

  # inbound twilio sms
  def twilio
    @message= Message.new(
      sid: params['SmsSid'],
      to: params['To'],
      from: params['From'],
      body: params['Body']
    )

    respond_to do |format|
      if @message.save
        format.xml { head 200 }
      else
        format.xml { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def authorize_twilio
    head 403 unless User.find_by(twilio_account_sid: params['AccountSid'])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/phone_numbers_helper.rb
module PhoneNumbersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SmsReceiver</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/phone_numbers/_form.html.erb
<%= form_with(model: phone_number) do |form| %>
  <% if phone_number.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(phone_number.errors.count, "error") %> prohibited this phone_number from being saved:</h2>

      <ul>
        <% phone_number.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :e164_number %>
    <%= form.text_field :e164_number %>
  </div>

  <div class="field">
    <%= form.label :twilio_sid %>
    <%= form.text_field :twilio_sid %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/phone_numbers/edit.html.erb
<h1>Editing Phone Number</h1>

<%= render 'form', phone_number: @phone_number %>

<%= link_to 'Show', @phone_number %> |
<%= link_to 'Back', phone_numbers_path %>

app/views/phone_numbers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Phone Numbers</h1>

<table>
  <thead>
    <tr>
      <th>E164 number</th>
      <th>Twilio sid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @phone_numbers.each do |phone_number| %>
      <tr>
        <td><%= phone_number.phone_number %></td>
        <td><%= phone_number.sid %></td>
        <td><%= link_to 'Show', phone_number_path(phone_number.phone_number) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Phone Number', new_phone_number_path %>

app/views/phone_numbers/new.html.erb
<h1>New Phone Number</h1>

<%= render 'form', phone_number: @phone_number %>

<%= link_to 'Back', phone_numbers_path %>

app/views/phone_numbers/show.html.erb
<p id="notice"><%= notice %></p>

<h2>Messages</h2>

Sent to <%= @phone_number.phone_number %>

<table>
  <thead>
    <tr>
      <th>SID</th>
      <th>From</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.sid %></td>
        <td><%= message.from %></td>
        <td><%= message.body %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Back', phone_numbers_path %>